// export const ADD_FAV = "ADD_FAV";
// export const REMOVE_FAV = "REMOVE_FAV";

///
// export const FILTER = "FILTER";
export const GET_ALL_GENRES = "GET_ALL_GENRES";
///

export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const FILTER_BY_GENRES = "FILTER_BY_GENRES";
export const ORDER = "ORDER";
export const ORDER_RATING = "ORDER_RATING";
export const FILTER_CREATED = "FILTER_CREATED";
export const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";
export const POST_VIDEOGAMES = "POST_VIDEOGAMES";
export const GET_GENRES = "GET_GENRES";
export const EDIT_VIDEOGAME = "EDIT_VIDEOGAME";
export const DELETE_VIDEOGAME = "DELETE_VIDEOGAME";
export const CLEAN_VIDEOGAMES = "CLEAN_VIDEOGAMES";
export const FILTER_PLATFORMS = "FILTER_PLATFORMS";
